version: '3'

services:
  api:
    build: ./src/
    ports:
      - "5000:5000"
    volumes:
      - "./src:/src"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: app.py
      FLASK_ENV: developments
      dbhost: db
      dbname: tarot
      dbuser: tarot
      dbpass: Tarot123#
    command: flask run -h 0.0.0.0
 # db:
 #   build: ./mysql/
 #   ports:
 #     - "32000:3306"
 #   volumes:
 #     - ./mysql/mysql_data:/var/lib/mysql
 #     - ./mysql/sqls:/docker-entrypoint-initdb.d
 #   environment:
 #     - TZ=Asia/Tokyo
 #     - MYSQL_ROOT_PASSWORD=root
 #     - MYSQL_USER=tarot
 #     - MYSQL_PASSWORD=Tarot123#
 #     - MYSQL_DATABASE=tarot
